# Iniciación en Python con Aplicaciones en Aceración (día 01)

**Dr. Edgar Ivan Castro Cedeño**

[edgar.castro@cinvestav.mx](mailto:edgar.castro@cinvestav.mx)

# 3. Numpy

## 3.1 Importar Numpy

Para utilizar la librería `numpy`, se requiere importarla al programa. Por convención, el módulo `numpy` se importa utilizando el álias `np`.

In [1]:
import numpy as np

## 3.2 Objeto Numpy Array

### 3.2.1 Atributos

Una parte fundamental de la librería `numpy` son las estructuras de datos que representan arreglos multidimensionales con datos homogéneos, i.e., todos los elementos en el arreglo tienen el mismo tipo de dato.

La estructura principal para un arreglo multidimensional en `numpy` es la clase `ndarray`. Además de contenter los datos del arreglo, esta estructura también contiene metadatos, tales como la forma, el tamaño, el tipo de datos, y otros atributos.


| Atributo | Descripción |
|----------|-----------------------|
| `Shape`  | Un tuple que contiene el número de elementos (i.e., la longitud) para cada dimensión (eje) del arreglo. |
| `Size`   | Número total de elementos en el arreglo. |
| `Ndim`   | Número de dimensions (ejes). |
| `nbytes` | Número de bytes utilizados para almacenar los datos. |
| `dtype`  | El tipo de datos de los elementos en el arreglo. |

In [71]:
data = np.array([[1, 2], [3, 4], [5, 6]])

In [72]:
type(data)

numpy.ndarray

In [3]:
def info_array(data):
    print(data)
    print(type(data))
    print("data.ndim: ", data.ndim)
    print("data.shape: ", data.shape)
    print("data.size: ", data.size)
    print("data.dtype: ", data.dtype)
    print("data.nbytes:", data.nbytes)

In [4]:
info_array(data)

[[1 2]
 [3 4]
 [5 6]]
<class 'numpy.ndarray'>
data.ndim:  2
data.shape:  (3, 2)
data.size:  6
data.dtype:  int64
data.nbytes: 48


### 3.2.2 Creación de Arrays

#### 3.2.2.1 Arrays generales

Los arrays se crean a partir de listas u otras estructuras similares.

In [5]:
# array de una dimensión (declarado a partir de una lista)
data = np.array([1, 2, 3, 4])
info_array(data)

[1 2 3 4]
<class 'numpy.ndarray'>
data.ndim:  1
data.shape:  (4,)
data.size:  4
data.dtype:  int64
data.nbytes: 32


In [74]:
# array de dos dimensiones (declarado a partir de una lista anidada)
data = np.array([[1, 2], [3, 4]])
info_array(data)

[[1 2]
 [3 4]]
<class 'numpy.ndarray'>
data.ndim:  2
data.shape:  (2, 2)
data.size:  4
data.dtype:  int64
data.nbytes: 32


#### 3.2.2.2 Arrays con valores constantes

Las funciones `np.zeros()` y `np.ones()` sirven para crear arrays llenos de ceros o unos, respectivamente. Toman como argumento un entero `int` o un tuple `tuple` que describe el número de elementos a lo largo de cada dimensión en el arreglo. Estas funciones tienen un argumento opcional para especificar el tipo de datos de los elementos en el array.

In [76]:
data = np.zeros((2, 3))
info_array(data)

data = np.ones(4)
info_array(data)

data= np.ones(4, dtype=np.int64)
info_array(data)

[[0. 0. 0.]
 [0. 0. 0.]]
<class 'numpy.ndarray'>
data.ndim:  2
data.shape:  (2, 3)
data.size:  6
data.dtype:  float64
data.nbytes: 48
[1. 1. 1. 1.]
<class 'numpy.ndarray'>
data.ndim:  1
data.shape:  (4,)
data.size:  4
data.dtype:  float64
data.nbytes: 32
[1 1 1 1]
<class 'numpy.ndarray'>
data.ndim:  1
data.shape:  (4,)
data.size:  4
data.dtype:  int64
data.nbytes: 32


#### 3.2.2.3 Arrays con secuencias incrementales

`numpy` cuenta con dos funciones, `np.arange()` y `np.linspace()` para crear arrays con datos con espaciado constante. Ambas funciones toman tres argumentos: los primeros dos son el valor inicial y final. El tercer argumento para `np.arange()` es el incremento, y para `np.linspace()` es el número de puntos en el array.

In [81]:
data = np.arange(0, 11, 2)
print('Note que np.arange() excluye el valor final')
print(data)
data = np.linspace(0.0, 10, 5)
print('Note que np.linspace() incluye el valor final')
print(data)

Note que np.arange() excluye el valor final
[ 0  2  4  6  8 10]
Note que np.linspace() incluye el valor final
[ 0.   2.5  5.   7.5 10. ]


La función `np.logspace()` es similar en funcionamiento a `np.linspace()`, pero los incrementos están distribuidos de forma logarítmica. Los primeros dos argumentos corresponden a las potencias respecto al argumento opcional `base`, cuyo valor por default es `10`.

In [83]:
data = np.logspace(0, 2, 3) # data points between 10**0 = 1 to 10**2=100
print(data)

data = np.logspace(0, 2, 3, base=2) # data points between 2**0 = 1 to 2**2=4
print(data)

[  1.  10. 100.]
[1. 2. 4.]


#### 3.2.2.4 Arrays tipo Meshgrid

La función `np.meshgrid()` se utiliza para generar mallas con coordenadas multi-dimensionales.

In [86]:
x = np.array([-1, 0, 1])
y = np.array([-1, 0, 1])

X, Y = np.meshgrid(x, y)

print(X)
print(Y)

[[-1  0  1]
 [-1  0  1]
 [-1  0  1]]
[[-1 -1 -1]
 [ 0  0  0]
 [ 1  1  1]]


Un caso de utilización común de arrays de dos-dimensiones, como `X`, `Y` en el ejemplo, es para evaluar funciones que dependen de dos variables `x`, `y`. 

Por ejemplo, para evaluar la expresión $z=(x^2 + y^2)$ para todas las combinaciones de valores `x`, `y`.

In [11]:
Z = (X**2 + Y**2)
print(Z)

[[2 1 2]
 [1 0 1]
 [2 1 2]]


## 3.3 Navegación y manipulación de Arrays

### 3.3.1 Arrays de una dimensión

Resumen de operaciones para navegar en Arrays:

| Expressión | Descripción |
|------------|-------------|
| `a[m]`     | Seleccionar el índice `m`, donde `m` es un entero (se cuanta a partir de 0). |
| `a[-m]`    | Seleccionar el índice `m` contando desde el final de la lista, donde `m` es un entero. El último elemento lleva índice `-1`, el penúltimo `-2`, y así sucesivamente. |
| `a[m:n]`   | Seleccionar elementos cuyo índice comienza en `m` y termina en `n-1` (`m`, `n` son enteros). |
| `a[:]` | Seleccionar todos los elementos de un eje dado |
| `a[:n]` | Seleccionar los elementos que van del índice `0` hasta el índice `n-1` (`n` es un entero). |
| `a[m:]`  | Seleccionar los elementos que van del índice `m` hasta el último elemento. |
| `a[m:n:p]`| Seleccionar elementos que van del índice `m` hasta el  `n` (excluyente), con incremento `p`. |
| `a[::-1]` | Seleccionar todos los elementos, revirtiendo el órden. |

In [12]:
a = np.arange(0, 11)
print(f'a = {a}')
print(f'a[0] = {a[0]}') # first element
print(f'a[-1] = {a[-1]}') # last element
print(f'a[4] = {a[4]}') # the fifth element, at index 4

a = [ 0  1  2  3  4  5  6  7  8  9 10]
a[0] = 0
a[-1] = 10
a[4] = 4


In [13]:
print(f'a = {a}')
print(f'a[1:-1] = {a[1:-1]}') # second to second-to-last element
print(f'a[1:-1:2] = {a[1:-1:2]}') # second to second-to-last element, with step 2

a = [ 0  1  2  3  4  5  6  7  8  9 10]
a[1:-1] = [1 2 3 4 5 6 7 8 9]
a[1:-1:2] = [1 3 5 7 9]


### 3.3.2 Arrays multi-dimensionales

In [88]:
A = np.identity(5)
print(A)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


Modificar elementos en el Array

In [91]:
for i in range(5):
    A[i,i] = i+2

A[3,4] = 4
print(A)

[[2. 0. 0. 0. 0.]
 [0. 3. 0. 0. 0.]
 [0. 0. 4. 0. 0.]
 [0. 0. 0. 5. 4.]
 [0. 0. 0. 0. 6.]]


Seleccionar filas o columnas

In [92]:
print(f'A[:,1] = \n {A[:,0]}') # primera columna
print(f'A[1,:] = \n {A[1,:]}') # segunda fila

A[:,1] = 
 [2. 0. 0. 0. 0.]
A[1,:] = 
 [0. 3. 0. 0. 0.]


### 3.3.3 Cambiar la forma de Arrays

La función `np.reshape()`, o el método `reshape` de la clase `ndarray` permiten modificar redimensionar los arrays. Esta operación únicamente modifica la manera en que la estructura de datos es interpretada.

In [17]:
data = np.array([[1, 2], [3, 4]])
info_array(data)

[[1 2]
 [3 4]]
<class 'numpy.ndarray'>
data.ndim:  2
data.shape:  (2, 2)
data.size:  4
data.dtype:  int64
data.nbytes: 32


In [18]:
d1 = np.reshape(data, (1, 4))
info_array(d1)

[[1 2 3 4]]
<class 'numpy.ndarray'>
data.ndim:  2
data.shape:  (1, 4)
data.size:  4
data.dtype:  int64
data.nbytes: 32


In [19]:
d2 = data.reshape(4)
info_array(d2)

[1 2 3 4]
<class 'numpy.ndarray'>
data.ndim:  1
data.shape:  (4,)
data.size:  4
data.dtype:  int64
data.nbytes: 32


La función `np.ravel()` y el método `flatten` de la clase `ndarray` permiten colapsar un array multi-dimensional en un array de una dimensión.


In [20]:
data = np.array([[1, 2], [3, 4]])
info_array(data)

[[1 2]
 [3 4]]
<class 'numpy.ndarray'>
data.ndim:  2
data.shape:  (2, 2)
data.size:  4
data.dtype:  int64
data.nbytes: 32


In [21]:
d1 = np.ravel(data)
info_array(d1)

[1 2 3 4]
<class 'numpy.ndarray'>
data.ndim:  1
data.shape:  (4,)
data.size:  4
data.dtype:  int64
data.nbytes: 32


In [22]:
d2 = data.flatten()
info_array(d2)

[1 2 3 4]
<class 'numpy.ndarray'>
data.ndim:  1
data.shape:  (4,)
data.size:  4
data.dtype:  int64
data.nbytes: 32


También es posible agregar nuevos ejes a un array, ya sea utilizando la función `np.reshape()`, o utilizando la palabra reservada `np.newaxis` cuando se desée agregar una eje vacío.

In [23]:
data = np.arange(0, 5)
info_array(data)

[0 1 2 3 4]
<class 'numpy.ndarray'>
data.ndim:  1
data.shape:  (5,)
data.size:  5
data.dtype:  int64
data.nbytes: 40


In [24]:
column = data[:, np.newaxis]
info_array(column)

[[0]
 [1]
 [2]
 [3]
 [4]]
<class 'numpy.ndarray'>
data.ndim:  2
data.shape:  (5, 1)
data.size:  5
data.dtype:  int64
data.nbytes: 40


In [25]:
row = data[np.newaxis, :]
info_array(row)

[[0 1 2 3 4]]
<class 'numpy.ndarray'>
data.ndim:  2
data.shape:  (1, 5)
data.size:  5
data.dtype:  int64
data.nbytes: 40


La función `np.expand_dims()` es otra alternativa para agregar dimensiones a un array.

In [26]:
data = np.arange(0, 5)
info_array(data)

[0 1 2 3 4]
<class 'numpy.ndarray'>
data.ndim:  1
data.shape:  (5,)
data.size:  5
data.dtype:  int64
data.nbytes: 40


In [27]:
column = np.expand_dims(data, axis=1)
info_array(column)

[[0]
 [1]
 [2]
 [3]
 [4]]
<class 'numpy.ndarray'>
data.ndim:  2
data.shape:  (5, 1)
data.size:  5
data.dtype:  int64
data.nbytes: 40


In [28]:
row = np.expand_dims(data, axis=0)
info_array(row)

[[0 1 2 3 4]]
<class 'numpy.ndarray'>
data.ndim:  2
data.shape:  (1, 5)
data.size:  5
data.dtype:  int64
data.nbytes: 40


### 3.3.4 Combinar Arrays

Las funciones `np.vstack()`, `np.hstack()` permiten empilar arrays de forma vertical u horizontal, respectivamente.

In [29]:
data = np.arange(5)
info_array(data)

[0 1 2 3 4]
<class 'numpy.ndarray'>
data.ndim:  1
data.shape:  (5,)
data.size:  5
data.dtype:  int64
data.nbytes: 40


In [30]:
vstack = np.vstack((data, data, data))
info_array(vstack)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]
<class 'numpy.ndarray'>
data.ndim:  2
data.shape:  (3, 5)
data.size:  15
data.dtype:  int64
data.nbytes: 120


In [31]:
column = np.expand_dims(data, axis=1)
vstack1 = np.vstack((column, column))
info_array(vstack1)

[[0]
 [1]
 [2]
 [3]
 [4]
 [0]
 [1]
 [2]
 [3]
 [4]]
<class 'numpy.ndarray'>
data.ndim:  2
data.shape:  (10, 1)
data.size:  10
data.dtype:  int64
data.nbytes: 80


In [32]:
data = np.arange(5)
info_array(data)

[0 1 2 3 4]
<class 'numpy.ndarray'>
data.ndim:  1
data.shape:  (5,)
data.size:  5
data.dtype:  int64
data.nbytes: 40


In [33]:
hstack = np.hstack((data, data))
info_array(hstack)

[0 1 2 3 4 0 1 2 3 4]
<class 'numpy.ndarray'>
data.ndim:  1
data.shape:  (10,)
data.size:  10
data.dtype:  int64
data.nbytes: 80


In [34]:
column = np.expand_dims(data, axis=1)
hstack1 = np.hstack((column, column, column))
info_array(hstack1)

[[0 0 0]
 [1 1 1]
 [2 2 2]
 [3 3 3]
 [4 4 4]]
<class 'numpy.ndarray'>
data.ndim:  2
data.shape:  (5, 3)
data.size:  15
data.dtype:  int64
data.nbytes: 120


## 3.4 Operaciones y funciones

### 3.4.1 Operaciones vectorizadas

El propósito de almacenar datos numéricos en arrays es poder procesarlo en lotes utilizando expresiones vectorizadas concizas, que permitan aplicar la misma operación a todos los elementos del array. Esta filosofía permite prescindir en muchos casos de la utilización de bucles de cálculo.

In [35]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])

In [36]:
print(f"{x}")
print("+")
print(f"{y}")
print(8*"=")
print(f"{x+y}")

[[1 2]
 [3 4]]
+
[[5 6]
 [7 8]]
[[ 6  8]
 [10 12]]


La vectorización de operaciones permite escribir código más claro, y con tiempos de ejecución más rápidos.

In [37]:
%%timeit
z = x + y

361 ns ± 8.78 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [38]:
%%timeit
z = np.zeros_like(x)
for i in range(len(x)):
    for j in range(len(y)):
        z[i,j] = x[i,j] + y[i,j]

3.19 µs ± 17.7 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


Es posible vectorizar una función que originalmente sólo puede operar elemento a elemento, utilizando la función `np.vectorize()` o usando arrays booleanos.

In [39]:
x = np.linspace(-1, 1, 11)

In [95]:
# La función de Heaviside, como está definida aquí, no permite trabajar con arrays
def heaviside(x):
    return 1 if x > 0 else 0

print(heaviside(-1))
print(heaviside(1))
#print(heaviside(x)) # esto produce un error

0
1


In [41]:
# vectorizar utilizando np.vectorize()
heaviside1 = np.vectorize(heaviside)

In [42]:
# vectorizar utilizando lógica booleana
def heaviside2(x):
    return 1 * (x>0)

La función creada 

In [43]:
print(heaviside1(x))
print(heaviside2(x))

[0 0 0 0 0 0 1 1 1 1 1]
[0 0 0 0 0 0 1 1 1 1 1]


La función `heaviside1()`, creada con `np.vectorize()` llama de forma individual a la función original para cada elemento del array. Es por esto que su ejecución es más lenta que la función `heaviside2()`, creada con lógica booleana es relativamente más rápida.

In [44]:
%%timeit
heaviside1(x)

7.72 µs ± 37 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [45]:
%%timeit
heaviside2(x)

1.87 µs ± 13.3 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


### 3.4.2 Operaciones aritméticas

Las operaciones artiméticas se realizan elemento a elemento.

In [46]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])
print(f'x = \n {x}')
print(f'y = \n {y}')

x = 
 [[1 2]
 [3 4]]
y = 
 [[5 6]
 [7 8]]


In [47]:
# Adición
print(f'x + y = \n {x+y}')

x + y = 
 [[ 6  8]
 [10 12]]


In [48]:
# Substracción
print(f'x - y = \n {x-y}')

x - y = 
 [[-4 -4]
 [-4 -4]]


In [49]:
# Multiplicación
print(f'x * y = \n {x*y}')

x * y = 
 [[ 5 12]
 [21 32]]


In [50]:
# División
print(f'x / y = \n {x / y}')

x / y = 
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]


### 3.4.3 Funciones que operan elemento a elemento

| Función | Descripción |
|----------------|-------------------------|
| `np.sin()`, `np.cos()`, `np.tan()` | Funciones trigonométricas |
| `np.arcsin()`, `np.arccos()`, `np.arctan()` | Funciones trigonométricas inversas |
| `np.sinh()`, `np.cosh()`, `np.tanh()` | Funciones trigonométricas hiperbólicas |
| `np.arcsinh()`, `np.arccosh()`, `np.arctanh()` | Funciones trigonométricas hiperbólicas inversas |
| `np.sqrt()` | Raíz cuadrada |
| `np.exp()` | Exponencial |
| `np.log()`, `np.log2()`, `np.log10()` | Logarítmos base e, 2, 10, respectivamente. |
| `np.add()`, `np.subtract()`, `np.multiply()`, `np.divide()` | Adición, substracción, multiplicación, división de dos arrays. |
| `np.power()` | Eleva el primer argumento a la potencia del segundo argumento (aplicada elemento a elemento) |
| `np.remainder()` | Restante de una división |
| `np.real()`, `np.imag()`, `np.conj()` | La parte real, imaginaria, y el complejo conjugado de los elementos en un array |
| `np.sign()`, `np.abs()` | El signo, y el valor absoluto. |
| `np.floor()`, `np.ceil()`, `np.rint()` | Convertir a números enteros |
| `np.round()` | Redondear a un número dado de decimales. |

In [51]:
x = np.linspace(0, np.pi, 5)
print(f"x = \n {np.round(x, decimals=4)}")
print(f"sin(x) = \n {np.round(np.sin(x), decimals=4)}")

x = 
 [0.     0.7854 1.5708 2.3562 3.1416]
sin(x) = 
 [0.     0.7071 1.     0.7071 0.    ]


In [52]:
t = np.linspace(0, np.e, 5)
print(f"t = \n {np.round(t, decimals=4)}")
print(f"exp(-t) = \n {np.round(np.exp(-t), decimals=4)}")

t = 
 [0.     0.6796 1.3591 2.0387 2.7183]
exp(-t) = 
 [1.     0.5068 0.2569 0.1302 0.066 ]


### 3.4.4 Funciones de agregación

| Función | Descripción |
|----------------|------------------|
| `np.mean()` | El promedio de todos los valores en el array. |
| `np.std()` | Desviación estándar. |
| `np.var()` | Varianza. |
| `np.sum()` | Suma de todos los elemetos. |
| `np.prod()` | Producto de todos los elementos. |
| `np.cumsum()` | Suma acumulada de todos los elementos. |
| `np.cumprod()` | Producto acumulado de todos los elementos. |
| `np.min()`, `np.max()` | Valor mínimo/máximo en un array. |
| `np.argmin()`, `np.argmax()` | La posición (índice) del valor mínimo/máximo en un array. |
| `np.all()` | Regresa `True` si todos los elementos en el array son diferentes de cero. |
| `np.any()` | Regresa `True` si algún elemento en el array es diferente de cero. |

Por default, estas funciones llevan a cabo la agregación sobre todo el array. Si se utiliza el argumento `axis`, y métodos de la clase `ndarray`, es posible controlar sobre cuál eje se lleva a cabo la agregación.

In [53]:
data = np.arange(1, 10).reshape(3, 3)
print(data)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [54]:
print(f"data.sum() = \n {data.sum()}")
print(f"data.sum(axis=0) = \n {data.sum(axis=0)}")
print(f"data.sum(axis=1) = \n {data.sum(axis=1)}")

data.sum() = 
 45
data.sum(axis=0) = 
 [12 15 18]
data.sum(axis=1) = 
 [ 6 15 24]


### 3.4.5 Operaciones booleanas y expresiones condicionales

Operadores booleanos que realizan comparaciones elemento a elemento

| Operador | Descripción |
|---|-----------|
| `<` | menor que. |
| `>` | mayor que. |
| `<=` | menor o igual a. |
| `>=` | mayor o igual a. |
| `==` | igual a. |
| `!=` | distinto a. |


In [55]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 3, 2, 1])
print(f"a < b = {a < b}")

a < b = [ True  True False False]


A veces es necesario llevar a cabo una agregación de los resultados booleanos, y esto se puede hacer con las funciones `np.all()` y `np.any()`.

In [56]:
print(f"np.all(a < b) ? {np.all(a < b)}")
print(f"np.any(a < b) ? {np.any(a < b)}")

np.all(a < b) ? False
np.any(a < b) ? True


Funciones de numpy para operaciones lógicas entre arrays

| Function | Description |
|----------|-------------|
| `np.where` | Escoge valores de dos arrays dependiendo de una condición dada como argumento. |
| `np.choose` | Escoge valores de una lista de arrays dependiendo de los valores dados por un índice de arrays. |
| `np.select` | Escorge valores de una lista de arrays dependiendo de una lista de condiciones. |
| `np.nonzero` | Regresa un array con indices de los elementos distintos de cero. |
| `np.logical_and` | Realiza una operación lógica `AND` elemento a elemento. |
| `np.logical_or`, `np.logical_xor` | Realiza una operación lógica `OR`/`XOR` elemento a elemento. |
| `np.logical_not` | Realiza una operación lógica `NOT` elemento a elemento. |

In [57]:
x = np.linspace(-1, 1, 5)
print(f'x = \n {x}')
print(f'x**2 = \n {x**2}')
print(f'x**3 = \n {x**3}')

x = 
 [-1.  -0.5  0.   0.5  1. ]
x**2 = 
 [1.   0.25 0.   0.25 1.  ]
x**3 = 
 [-1.    -0.125  0.     0.125  1.   ]


In [58]:
np.where(x < 0, (x**2), (x**3))

array([1.   , 0.25 , 0.   , 0.125, 1.   ])

In [59]:
np.select([x < -1, x < 0, x >= 0], [x, x**2, x**3])

array([1.   , 0.25 , 0.   , 0.125, 1.   ])

### 3.4.6 Operaciones de conjuntos

| Función | Descripción |
|----------|-------------|
| `np.unique` | Crea un nuevo array con elementos únicos en un conjunto, donde cada valor aparece una sola vez.  |
| `np.in1d` | Prueba para conocer la existencia de un array (conjunto) de elementos en otro array (conjunto). |
| `np.intersect1d` | Regresa un array con la intersección de dos conjuntos contenidos en dos arrays. |
| `np.setdiff1d` | Regresa un array con la diferencia de de dos conjuntos, los elementos que están contenidos en uno pero no en los dos arrays. |
| `np.union1d` | Regresa un array con la unión de dos conjuntos, los elementos que están contenidos en ambos arrays. |

In [60]:
a = np.unique([1, 2, 3, 3])
b = np.unique([2, 3, 4, 4, 5, 6, 5])
print(a)
print(b)

[1 2 3]
[2 3 4 5 6]


In [61]:
print(np.in1d(a, b))
print(np.in1d(b, a))

[False  True  True]
[ True  True False False False]


In [62]:
print(f"Intersección: {np.intersect1d(a, b)}")
print(f"Diferencia(a, b): {np.setdiff1d(a, b)}")
print(f"Diferencia(b, a): {np.setdiff1d(b, a)}")
print(f"Union(a, b) = {np.union1d(a, b)}")

Intersección: [2 3]
Diferencia(a, b): [1]
Diferencia(b, a): [4 5 6]
Union(a, b) = [1 2 3 4 5 6]


### 3.4.7 Operaciones con arrays

| Función | Descrición |
|----------|-------------|
| `np.transpose()`, `np.ndarray.transpose`, `np.ndarray.T` | Transpuesta de un array. |
| `np.flip()` | Revierte el orden de los elementos de un array |
| `np.fliplr()` / `np.flipud()` | Revierte el orden de los elementos en cada  fila/columna. |
| `np.rot90()` | rota los elementos de los primeros ejes 90 grados. |
| `np.sort()`, `np.ndarray.sort` | Ordena los elementos de un array sobre el eje especificado (por default el último eje). |

In [63]:
data = np.arange(9).reshape(3, 3)
print(data)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [64]:
print(f"Transpuesta: \n {np.transpose(data)}")
print(f"flip: \n {np.flip(data)}")
print(f"fliplr: \n {np.fliplr(data)}")
print(f"flipud: \n {np.flipud(data)}")
print(f"Rotacion 90°: \n {np.rot90(data)}")

Transpuesta: 
 [[0 3 6]
 [1 4 7]
 [2 5 8]]
flip: 
 [[8 7 6]
 [5 4 3]
 [2 1 0]]
fliplr: 
 [[2 1 0]
 [5 4 3]
 [8 7 6]]
flipud: 
 [[6 7 8]
 [3 4 5]
 [0 1 2]]
Rotacion 90°: 
 [[2 5 8]
 [1 4 7]
 [0 3 6]]


In [65]:
data = np.random.randint(1, 10, size=10)
print(data)

[7 2 6 2 3 5 7 5 8 8]


In [66]:
print(f"orden de menor a mayor: \n {np.sort(data)}")
print(f"orden de mayor a menor: \n {np.flip(np.sort(data))}")

orden de menor a mayor: 
 [2 2 3 5 5 6 7 7 8 8]
orden de mayor a menor: 
 [8 8 7 7 6 5 5 3 2 2]


### 3.4.8 Operaciones con vectores y matrices

| Función | Descripción |
|----------------|--------------------------|
| `np.dot` | Multiplicación de matrices (producto punto) entre dos arrays, que representan vectores, matrices o tensores. |
| `np.inner` | Multiplicación escalar (producto interior) entre una matriz y la transpuesta de otra matriz |
| `np.cross` | The cross product between two arrays that represent vectors. |
| `np.tensordot` | Dot product along specified axes of multidimensional arrays. |
| `np.outer` | Outer product (tensor product of vectors) between two arrays representing vectors. |
| `np.kron` | Kronecker product (tensor product of matrices) between arrays representing matrices and higher-dimensional arrays. |
| `np.einsum` | Evaluates Einstein's summation convention for multidimensional arrays. |

In [67]:
A=np.array([[1,2],
            [-2,1]])
print(f"A = \n{A}")
print(f"AT = \n{A.T}") # A.T es equivalente a np.transpose(A)

A = 
[[ 1  2]
 [-2  1]]
AT = 
[[ 1 -2]
 [ 2  1]]


In [68]:
print(f"A.A = \n{np.dot(A, A)}")
print(f"A.AT = \n{np.dot(A, A.T)}") 
print(f"A.AT = \n{np.inner(A, A)}")

A.A = 
[[-3  4]
 [-4 -3]]
A.AT = 
[[5 0]
 [0 5]]
A.AT = 
[[5 0]
 [0 5]]


In [69]:
a = np.array([1, 0, 0])
b = np.array([0, 1, 0])
print(f"a = \n{a}")
print(f"b = \n{b}")

a = 
[1 0 0]
b = 
[0 1 0]


In [70]:
print(f"a x b = \n{np.cross(a,b)}")

a x b = 
[0 0 1]


## 3.5 Referencias / Documentación

- https://www.python.org/doc/

- https://numpy.org/doc/stable/

- https://link.springer.com/book/10.1007/978-1-4842-4246-9